### ISSUE TITLE
[Install Software] Incorrect branch referenced binder URL

### ISSUE THREAD

**Issue by ryanRATM** [crazy4pi314/learn-qc-with-python-and-qsharp#15]
url should be: https://mybinder.org/v2/gh/crazy4pi314/learn-qc-with-python-and-qsharp/main

**Comment by crazy4pi314** [comment]
Thanks @ryanRATM! Sorry for the delay but you are right. As a work-around to keep the book links working for now, we are mirroring main on master so they all should work <3
