### ISSUE TITLE
Qubit reset unnecessary in send_classical_bit function

### ISSUE THREAD

**Issue by hettlage** [crazy4pi314/learn-qc-with-python-and-qsharp#9]
The function `send_classical_bit` in `ch03/qkd.py` includes a call to the qubit's reset method. But from what I can see, this shouldn't be necessary as the `using_qubit` context manager calls this method as well.

**Comment by crazy4pi314** [comment]
Thanks for calling this out! You're quite right that the reset is technically extraneous, but we've written this the way we did so as to match how you might write Q# programs with explicit `Reset` calls later in the book. Thanks again for pointing this out!
